Use outbox pattern for publishing events
pablocom/PersonalSite.Backend pull request #19
Opened 2022-10-02 21:13 UTC by pablocom

2022-10-11 18:13 UTC, ugm2 requested changes
These issues should be addressed before merging

2022-10-11 18:13 UTC, ugm2 commented on src/PersonalSite.Tests/PersonalSite.UnitTests/FakeInMemoryPersonalSiteDbContext.cs
> +    public DbSet<JobExperience> JobExperiences { get; set; }
Please review the warnings in the github action run and judge yourself if you need to change anything

2022-10-15 09:33 UTC, pablocom commented on src/PersonalSite.Persistence/Events/JobExperienceAddedHandlerForEventStore.cs
> +        // TODO: Guid and DateTime should come from a provider to be easily testable
I will address it in this PR

2022-10-17 17:18 UTC, ugm2 approved these changes
Changes seem okay and all comments have been addressed. Good to go!

2022-10-17 17:19 UTC, merged